name: simplify_the_task
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  go_router: ^9.0.0
  path_provider: ^2.0.14
  flutter_bloc: ^8.1.2
  logger: ^1.4.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dio: ^5.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  uuid: ^3.0.7
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.4
  firebase_crashlytics: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  isar_generator: ^3.1.0+1
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
